import React from 'react'
import Head from "next/head";

const collections = () => {
  return (
    <div>
       <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Yo</h1>
    </div>
  )
}

export default collections