import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useEffect } from "react";
import next from "next";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head></div>
  );
};

export default Home;
