import type { NextPage } from "next";
import Head from "next/head";
import PlaylistCard from "../components/App/PlaylistCard";
import TopCharts from "../components/App/TopCharts";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Homepage</h1> */}
      <div>
        <div className={styles.top}>
          <PlaylistCard />
          <TopCharts />
        </div>
      </div>
    </div>
  );
};

export default Home;
