import type { NextPage } from "next";
import Head from "next/head";
import NewReleases from "../components/App/NewReleases";
import PlaylistCard from "../components/App/PlaylistCard";
import TopCharts from "../components/App/TopCharts";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.top}>
        <PlaylistCard />
        <TopCharts />
      </div>
      <div className={styles.newReleases}>
        <NewReleases />
      </div>
      <div className={styles.newReleases}>
        <NewReleases />
      </div>
      <div className={styles.newReleases}>
        <NewReleases />
      </div>
    </div>
  );
};

export default Home;
